---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: user1
spec:
  project: workshops
  source:
    path: manifests
    repoURL: https://github.com/user1/REPO.git
    targetRevision: HEAD
  destination:
    namespace: workshop-user1
    name: ml-prague-workshop
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
